### ISSUE TITLE
installation on cluster

### ISSUE THREAD

**Issue by mfrancesconi81** [pkathail/magic#17]
Is there a way to install magic in a local folder and run it on a cluster?

Thanks!

M.

**Comment by dvdijk** [comment]
so you're not able to install the requirements on the cluster?

**Comment by dvdijk** [comment]
if the issue is installing it into a specific location:
sudo pip3 install --install-option="--prefix=$PREFIX_PATH" .

and use --ignore-installed to force all dependencies to be reinstalled using this new prefix

http://stackoverflow.com/questions/2915471/install-a-python-package-into-a-different-directory-using-pip

**Comment by laughnea** [comment]
The python distribution you use should be installed in a folder for which you have full permissions (read/write/execute).  Without the ability to modify the python install, I ran into troubles installing on server..
